version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5050/api
        VITE_SOCKET_URL: http://localhost:5050
    container_name: lychat_client
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - lychat_network

networks:
  lychat_network:
    driver: bridge