version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        VITE_API_URL: http://192.168.252.130:30008/api
        VITE_SOCKET_URL: http://192.168.252.130:30008
    container_name: lychat_client
    restart: unless-stopped
    ports:
      - "30088:80"
    networks:
      - lychat_network

networks:
  lychat_network:
    driver: bridge